import itertools

inver_letter = [
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "j",
    "k",
    "l",
    "m",
    "n",
    "p",
    "q",
    "r",
    "s",
    "x",
    "y",
    "z",
]

words_list = [
    "conseguiu",
    "ninguém",
    "assalto",
    "alguém",
    "exame",
    "embaixo",
    "fez",
    "também",
    "faz",
    "guerra",
    "exemplo",
    "caiu",
    "enxergar",
    "almoço",
    "vez",
    "relógio",
    "jeito",
    "disse",
    "árvore",
    "borracha",
    "pegue",
    "saudade",
    "assim",
    "amanhã",
    "correr",
    "brincar",
    "homem",
    "gente",
    "viajar",
    "certo",
    "encontrou",
    "quente",
    "cabeça",
    "professora",
    "futebol",
    "feliz",
    "ajuda",
    "fazer",
    "tenho",
    "tempo",
    "tesoura",
    "muito",
    "quando",
    "cachorro",
    "então",
    "presente",
    "bruxa",
    "animal",
    "girafa",
    "carro",
    "porque",
    "galinha",
    "menino",
    "casa",
    "escola",
]


# Gerando todas as permutações do grupo de palavras selecionadas e salvando o resultado em um arquivo
with open("permutations.txt", "w") as file:
    for word in words_list:
        result = itertools.permutations(word)
        for perm in result:
            file.write(f"{''.join(perm)}\n")
